parameters:
  doctrine.entity.map.file: 'entitymap'
  doctrine.entity.map.extension: '.orm.yml'

services:
#  entity.hydrator.doctrine:
#    class: Vainyl\Doctrine\ORM\Entity\Hydrator\DoctrineEntityHydrator
#    arguments: ['@entity.manager.doctrine']
  doctrine.configuration.orm:
    class: Doctrine\ORM\Configuration
    factory: ['@doctrine.configuration.factory.orm', 'getConfiguration']
    arguments:
      - '@doctrine.cache.apcu'
      - '@app.environment'
      - '%doctrine.entity.map.file%'
      - '%doctrine.entity.map.extension%'
  doctrine.configuration.factory.orm:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineConfigurationFactory
    arguments: ['@extension.storage']
  doctrine.entity.manager:
    class: Vainyl\Doctrine\ORM\Entity\DoctrineEntityManager
    factory: ['@doctrine.entity.manager.factory', 'create']
    arguments:
      - '@database.doctrine.orm'
      - '@doctrine.configuration.orm'
      - '@doctrine.event.manager'
      - '@time.factory'
  doctrine.entity.manager.factory:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineEntityManagerFactory
  connection.factory.doctrine.orm:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineConnectionFactory
    arguments: ['@connection.storage']
  database.factory.doctrine.orm:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineDatabaseFactory
    arguments: ['@connection.storage', '@doctrine.configuration.orm', '@doctrine.event.manager']
  collection.factory.sequence.entity:
    decorates: collection.factory.sequence
    decoration_priority: 600
    class: Vainyl\Doctrine\ORM\Operation\Decorator\DoctrineCollectionFactoryDecorator
    arguments: ['@collection.factory.sequence.entity.inner', '@doctrine.entity.manager']
  entity.operation.factory.doctrine:
    class: Vainyl\Doctrine\ORM\Operation\Factory\DoctrineEntityOperationFactory
    arguments: ['@operation.factory', '@doctrine.entity.manager']