services:
#  entity.hydrator.doctrine:
#    class: Vainyl\Doctrine\ORM\Entity\Hydrator\DoctrineEntityHydrator
#    arguments: ['@entity.manager.doctrine']
  doctrine.configuration.orm:
    class: Doctrine\ORM\Configuration
    factory: ['@doctrine.configuration.factory.orm', 'getConfiguration']
    arguments:
      - '@doctrine.cache.apcu'
      - '@app.environment'
      - 'yaml'
      - 'entitymap'
      - '.orm.yml'
      - 'Proxy'
      - 'doctrine'
  doctrine.configuration.factory.orm:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineORMConfigurationFactory
    arguments: ['@extension.storage']
  doctrine.entity.manager:
    class: Vainyl\Doctrine\ORM\Entity\DoctrineEntityManager
    factory: ['@doctrine.entity.manager.factory', 'create']
    arguments:
      - '@database.doctrine.orm'
      - '@doctrine.configuration.orm'
      - '@doctrine.event.manager'
      - '@time.factory'
  doctrine.entity.manager.factory:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineEntityManagerFactory
  doctrine.connection.factory:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineORMConnectionFactory
    arguments: ['@connection.storage']
  database.factory.doctrine.orm:
    class: Vainyl\Doctrine\ORM\Factory\DoctrineORMDatabaseFactory
    arguments: ['@doctrine.connection.factory', '@doctrine.configuration.orm', '@doctrine.event.manager']
  collection.factory.sequence.entity:
    decorates: collection.factory.sequence
    decoration_priority: 600
    class: Vainyl\Doctrine\ORM\Operation\Decorator\DoctrineCollectionFactoryDecorator
    arguments: ['@collection.factory.sequence.entity.inner', '@doctrine.entity.manager']
  entity.operation.factory.doctrine:
    class: Vainyl\Doctrine\ORM\Operation\Factory\DoctrineEntityOperationFactory
    arguments: ['@operation.factory', '@doctrine.entity.manager']
  app.bootstrapper.doctrine.orm.type:
    class: Vainyl\Doctrine\ORM\Bootstrapper\DoctrineTypeBootstrapper
    arguments: ['@database.doctrine.orm', '@time.factory']
    tags:
      - {name: 'bootstrapper'}
  app.bootstrapper.doctrine.orm.proxy:
    class: Vainyl\Doctrine\ORM\Bootstrapper\DoctrineProxyBootstrapper
    arguments: ['@app.environment']
    tags:
      - {name: 'bootstrapper'}